### ISSUE TITLE
无法获取数据

### ISSUE THREAD

**Issue by funengqing** [arcticfox1919/flutter_new_retail#1]
1.在电脑(ip:192.168.0.161)本身可以访问开形如 http://127.0.0.1:8080/api/store 的数据
2.同一局域网下其他终端均无法访问192.168.161:8080/api/store

**Comment by arcticfox1919** [comment]
端口是8081，不是8080。先 ping 一下你的IP，看一下是否能通
@funengqing

**Comment by funengqing** [comment]
在电脑是可以访问
![1](https://user-images.githubusercontent.com/33955671/67257512-e84f8580-f4be-11e9-869f-18c86dfcb8e7.png)

电脑无线ip
![2](https://user-images.githubusercontent.com/33955671/67257537-074e1780-f4bf-11e9-9929-6bc29824dea7.png)

换成本机ip也可以访问
![5](https://user-images.githubusercontent.com/33955671/67257705-cdc9dc00-f4bf-11e9-8849-9fde82e5e6f8.png)


用手机来访问结果不行
![4](https://user-images.githubusercontent.com/33955671/67257559-2482e600-f4bf-11e9-8d87-267395856ef4.png)

商品应该是8080吧，就为启动的时候显示的是8080商品,改成8081后电脑和手机都访问不了

![3](https://user-images.githubusercontent.com/33955671/67257580-467c6880-f4bf-11e9-878d-51f8f4d60718.png)

----------分割线----------------
1.会不会是环境问题，要装Go的环境吗

**Comment by arcticfox1919** [comment]
服务器端口未固定，已添加配置文件指定，下载最新的测试服务器即可
