### ISSUE TITLE
api测试服务器地址怎么运行mac版的

### ISSUE THREAD

**Issue by heyangJob** [arcticfox1919/flutter_new_retail#3]
api测试服务器地址怎么运行mac版的

**Comment by arcticfox1919** [comment]
下载mac版测试服务器运行，确定mac电脑和手机在同一局域网内即可

**Comment by heyangJob** [comment]
双击api运行，    提示register db Ping `default`, unable to open database file
must have one register DataBase alias named `default`

**Comment by arcticfox1919** [comment]
@heyangJob 
既然使用Mac电脑怎么会用鼠标执行程序呢？应在终端中执行命令运行，`./api`
然后看一下报什么错，如果是权限问题，使用 `chmod`命令给整个文件夹加可读写可可执行的权限

**Comment by heyangJob** [comment]
可以了，愚钝了

**Comment by arcticfox1919** [comment]
可以关闭
